branches:
  only:
    - master

language: python

matrix:
  include:
    #- os: linux
    #  python: 2.7
    #- os: linux
    #  python: 3.6
    - os: osx
      python: 2.7
      language: generic

sudo: required

install:
  - source conda_installer.sh
  - conda upgrade conda
  - conda install conda-build anaconda-client
  - conda upgrade conda-build
  - conda config --set anaconda_upload no
  - conda config --add channels conda-forge
  - conda install gcc

#if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
#    conda config --set anaconda_upload yes;
#    python login.py;
#else
#    conda config --set anaconda_upload no;
#fi

  
#script: travis_wait 10 ./build_linux.sh
script: ./build_linux.sh


notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always

