branches:
  only:
    - master

language: python

matrix:
  include:
    - os: linux
      python: 2.7
    #- os: linux
    #  python: 3.6
    #- os: osx
    #  language: generic

sudo: required

install:
  - source conda_installer.sh
  - conda install conda-build anaconda-client
  #- conda config --add channels gmatteo
  - conda config --set anaconda_upload no

  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  #     brew update;
  #     brew install gcc;
  #  fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #     sudo apt-get install liblapack-dev libblas-dev;
  #  fi
  #- pip install pip --upgrade
  #- pip install -q -r requirements.txt --upgrade

script: travis_wait 10 ./build_linux.sh

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always