branches:
  only:
    #- master
    - foobar

language: python

# We don't actually use the Travis Python but conda
matrix:
  include:
    - os: linux
      python: 2.7
      env: PYTHON_VERSION=2.7
    - os: osx
      python: 2.7
      language: generic
      env: PYTHON_VERSION=2.7

#sudo: required

install:
  - source ./scripts/conda_installer.sh
  - conda upgrade conda
  - conda install conda-build 
  #- conda install anaconda-client
  - conda upgrade conda-build
  - conda config --set anaconda_upload no
  - conda config --add channels conda-forge
  - conda install gcc

script: ./scripts/build_linux.sh

notifications:
  email:
    recipients:
      - gmatteo@gmail.com
    on_success: change
    on_failure: always
