{% set version = "2.2.2" %}

package:
    name: libxc
    version: {{ version }} 

build:
    number: 0
    #string: libxc

source:
    fn: libxc-{{ version }}.tar.gz
    url: http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-{{ version }}.tar.gz
    sha256: 6ca1d0bb5fdc341d59960707bc67f23ad54de8a6018e19e02eee2b16ea7cc642


requirements:
    build:
        - gcc  
        - libgfortran  
    run:
        - libgfortran  

# Note: tests are run when building the package, they are not accessible in the installed package.
test:
  commands:
    - test -f ${PREFIX}/lib/libxc.a        # [not win]
    - test -f ${PREFIX}/lib/libxcf90.a     # [not win]
    - conda inspect linkages -p ${PREFIX} libxc  # [not win]
    - conda inspect linkages -p ${PREFIX} libxcf90  # [not win]
    - conda inspect objects -p ${PREFIX} libnetcdf  # [osx]
    - conda inspect objects -p ${PREFIX} libxcf90  # [osx]

about:
    home: http://www.tddft.org/programs/octopus/wiki/index.php/Libxc
    license: LGPL 3
    summary: | 
       Libxc is a library of exchange-correlation functionals for density-functional theory. 
       The aim is to provide a portable, well tested and reliable set of exchange and correlation functionals  
       that can be used by all the ETSF codes and also other codes.

extra:
  recipe-maintainers:
    - gmatteo
