package:
    name: libxc
    version: "2.2.2"

source:
    fn: libxc-2.2.2.tar.gz
    url: http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-2.2.2.tar.gz
    md5: 2edab8c06b24feeb3b82bbb3ebf3e7b3

requirements:
    build:

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: http://www.tddft.org/programs/octopus/wiki/index.php/Libxc
    license: GNU General Public License (GPL)
    summary: 'Libxc is a library of exchange-correlation functionals for density-functional theory. The aim is to provide a portable, well tested and reliable set of exchange and correlation functionals that can be used by all the ETSF codes and also other codes.
