{% set version = "2.2.2" %}

package:
    name: libxc
    version: {{ version }} 

source:
    fn: libxc-{{ version }}.tar.gz
    url: http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-{{ version }}.tar.gz
    sha256: aa

requirements:
    build:
        - gcc  
        - libgfortran  
    run:
        - libgfortran  

# Note: tests are run when building the package, they are not accessible in the installed package.
test:
  commands:
    - test -f ${PREFIX}/lib/libxc.so        # [linux]
    - test -f ${PREFIX}/lib/libxcf90.so     # [linux]
    - test -f ${PREFIX}/lib/libxc.dylib     # [osx]
    - test -f ${PREFIX}/lib/libxcf90.dylib  # [osx]

about:
    home: http://www.tddft.org/programs/octopus/wiki/index.php/Libxc
    license: LGPL 3
    summary: | 
       Libxc is a library of exchange-correlation functionals for density-functional theory. 
       The aim is to provide a portable, well tested and reliable set of exchange and correlation functionals  
       that can be used by all the ETSF codes and also other codes.

extra:
  recipe-maintainers:
    - gmatteo
