# Credits to jeanconn for the package https://binstar.org/jeanconn/fftw
{% set version = "3.3.6" %}

package:
    name: fftw
    version: {{ version }}

build:
    number: 0
    string: fftw_fortran

source:
    fn: fftw-{{ version }}.tar.gz
    url: http://www.fftw.org/fftw-{{ version }}-pl1.tar.gz
    sha256: 1ef4aa8427d9785839bc767f3eb6a84fcb5e9a37c31ed77a04e7e047519a183d

requirements:
    build:
        - gcc  
        - libgfortran 

# Note: tests are run when building the package, they are not accessible in the installed package.
test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libfftw3f.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3.a)           # [not win]
    #- exit $(test -f ${PREFIX}/lib/libfftw3l.a)          # [not win]
    #- exit $(test -f ${PREFIX}/lib/libfftw3f_threads.a)  # [not win]
    #- exit $(test -f ${PREFIX}/lib/libfftw3_threads.a)   # [not win]
    #- exit $(test -f ${PREFIX}/lib/libfftw3l_threads.a)  # [not win]
    - conda inspect linkages -p ${PREFIX} libfftw3f # [not win]
    - conda inspect linkages -p ${PREFIX} libfftw3  # [not win]
    - conda inspect objects -p ${PREFIX} libfftw3f  # [osx]
    - conda inspect objects -p ${PREFIX} libfftw3   # [osx]


about:
    home: http://fftw.org
    license: GPL 2
    summary: 'The fastest Fourier transform in the west.'

extra:
  recipe-maintainers:
    - gmatteo
