{% set version = "3.2.3b" %}
{% set libxc_version = '2.2.2' %}

package:
    name: oncvpsp
    version: {{ version }}

build:
    number: 0
    string: libxc_{{ libxc_version }}

source:
    fn: oncvpsp-{{ version }}.tar.gz
    url: http://www.mat-simresearch.com/oncvpsp-{{ version }}.tar.gz
    sha256: c9ef32f399361802b7a0fddd38feaa9ca113f48e018a3e3999402ac9e8aed2fc

requirements:
    build:
        - gcc  
        - libgcc 
        - libgfortran  
        - openblas
        - libxc  {{ libxc_version }}
    run:
        - libgcc       
        - libgfortran  
        - openblas
        - libxc  {{ libxc_version }}

# Note: tests are run when building the package, they are not accessible in the installed package.
test:
  commands:
    - test -x ${PREFIX}/bin/oncvpspnr.x
    - test -x ${PREFIX}/bin/oncvpsp.x   
    - test -x ${PREFIX}/bin/oncvpspr.x

about:
    home: http://www.mat-simresearch.com/
    license: GPL
    summary: | 
        Open-source pseudopotential code ONCVPSP
        to generate norm-conserving pseudopotentials using the approach 
        described in Phys. Rev. B 88, 085117 (2013)).
