{% set version = "4.0.0.14" %}
{% set libxc_version = '2.2.2' %}

package:
    name: atompaw
    version: {{ version }}

source:
    fn: atompaw-{{ version }}.tar.gz
    url: http://users.wfu.edu/natalie/papers/pwpaw/atompaw-{{ version}}.tar.gz
    sha256: foobar

requirements:
    build:
        - gcc  
        - libgcc
        - libgfortran  
        - openblas
        - libxc  {{ libxc_version }}
    run:
        - libgcc       
        - libgfortran  
        - openblas
        - libxc  {{ libxc_version }}

# Note: tests are run when building the package, they are not accessible in the installed package.
test:
  commands:
    - test -x ${PREFIX}/bin/atompaw

about:
    home: http://users.wfu.edu/natalie/papers/pwpaw/man.html
    license: GPL 
    summary: | 
        A Projector Augmented Wave (PAW) code for generating atom-centered functions.
        Official website: http://pwpaw.wfu.edu
        User's guide: ~/doc/atompaw-usersguide.pdf

extra:
  recipe-maintainers:
    - gmatteo
