{% set version = "4.0.0.14" %}
{% set libxc_version = '2.2.2' %}

package:
    name: atompaw
    version: {{ version }}

build:
    number: 0

source:
    fn: atompaw-{{ version }}.tar.gz
    url: http://users.wfu.edu/natalie/papers/pwpaw/atompaw-{{ version }}.tar.gz
    sha256: 8163974c8af93d8257b2e8db90eda635da64055faef3543cd4e74eb4a4a73d77

build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    # See https://github.com/ContinuumIO/anaconda-issues/issues/739
    rpaths:
      - lib/
      - lib64/


requirements:
    build:
        - gcc  
        - libgcc
        - libgfortran  
        - openblas
        - libxc  {{ libxc_version }}
    run:
        - libgcc       
        - libgfortran  
        - openblas
        - libxc  {{ libxc_version }}

# Note: tests are run when building the package, they are not accessible in the installed package.
test:
  commands:
    - test -x ${PREFIX}/bin/atompaw
    - test -x ${PREFIX}/bin/graphatom
    - test -f ${PREFIX}/lib/libatompaw.a    # [not win]
    #- conda inspect linkages -p ${PREFIX} libatompaw # [not win]
    #- conda inspect objects -p ${PREFIX} libatompaw  # [osx]

about:
    home: http://users.wfu.edu/natalie/papers/pwpaw/man.html
    license: GPL 
    summary: | 
        A Projector Augmented Wave (PAW) code for generating atom-centered functions.
        Official website: http://pwpaw.wfu.edu
        User's guide: ~/doc/atompaw-usersguide.pdf

extra:
  recipe-maintainers:
    - gmatteo
