{% set name = "abipy" %}
{% set version = "0.4.0" %}
#{% set md5 = "af9bc5cf7d5ca1a56ff73e2a65c5bcbd" %}
#55fd776786979ac5362ce37aa4a3c993

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #md5: {{ md5 }}
  git_tag: {{ version }}
  git_url: https://github.com/abinit/abipy.git


build:
  number: 0
  #script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python {{ python }}
    - setuptools
    - six
    - prettytable
    - tabulate
    - apscheduler ==2.1.0
    - pydispatcher >=2.0.5
    - tqdm
    - html2text
    - pyyaml >=3.11
    - pandas
    - numpy
    - scipy
    - spglib
    - pymatgen ==2018.3.14
    - netcdf4
    - matplotlib
    - seaborn
  run:
    - python
    - setuptools
    - six
    - prettytable
    - tabulate
    - apscheduler ==2.1.0
    - pydispatcher >=2.0.5
    - tqdm
    - html2text
    - pyyaml >=3.11
    - pandas
    - numpy
    - scipy
    - spglib
    - pymatgen ==2018.3.14
    - netcdf4
    - matplotlib
    - seaborn

test:
  commands:
    - abidoc.py man ecut
  imports:
    - abipy
    - abipy.abilab
    - abipy.abio
    - abipy.core
    - abipy.data
    - abipy.dfpt
    - abipy.dynamics
    - abipy.electrons
    - abipy.flowtk
    - abipy.waves

  # You can also put a file called run_test.py in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL2
  home: https://github.com/abinit/abipy
  summary: 'Python package to automate ABINIT calculations and analyze the results.'
  description: |
    AbiPy is a Python library to analyze the results produced by ABINIT, an open-source program for the 
    ab-initio calculations of the physical properties of materials within Density Functional Theory and 
    Many-Body perturbation theory. It also provides tools to generate input files and workflows to 
    automate ab-initio calculations and typical convergence studies. 
    AbiPy is interfaced with Pymatgen and this allows users to benefit from the different tools 
    and python objects available in the pymatgen ecosystem
  doc_url: https://abinit.github.io/abipy
  dev_url: https://github.com/abinit/abipy

extra:
  recipe-maintainers:
    - gmatteo
