{% set name = "abiout" %}
#{% set version = "1.0.0" %}

package:
    name: {{ name }}
    #version: {{ version }}

build:
    number: 0
    skip: True  # [win]
    #rpaths:
    #  - lib/
    #  - lib64/

source:
    #git_tag: {{ version }}
    git_url: https://github.com/abinit/abiout.git

# sudo apt-get install g++ autotools-dev automake autoconf m4 libtool libncurses5-dev libjpeg8-dev libpng-dev libnetcdf-dev libcurl3-dev libfreetype6-dev libglfw3-dev libeigen3-dev fontconfig ttf-ubuntu-font-family libxml2-dev gnuplot-qt libyaml-cpp-dev libfftw3-dev libssh-dev cxxtest
requirements:
  host:
    - m4
    - autoconf
    - automake
    - libtool
    - cxxtest
    - {{ compiler('cxx') }}
    # 
    - curl
    - libssh2
    - libpng
    - libxml2
    - freetype
    - eigen
    - fftw
    - gnuplot
    - yaml-cpp
    - glfw
    - libnetcdf * nompi_*
    - hdf5 * nompi_*

  run:
    - curl
    - libssh2
    - libpng
    - libxml2
    - freetype
    - eigen
    - fftw
    - gnuplot
    - yaml-cpp
    - glfw
    - libnetcdf * nompi_*
    - hdf5 * nompi_*

test:
  commands:
    - test -x ${PREFIX}/bin/abinit

#about:
#    home: https://www.abinit.org/
#    license: GPL
#    summary: "ABINIT is a quantum chemistry software based on the DFT (Density Functional Theory) method."
#    description: |
#        (for molecules). In addition to the main ABINIT code, different  utility programs are provided.
#    doc_url: http://www.abinit.org/doc/helpfiles/for-v8.0/users/new_user_guide.html
#    dev_url: https://github.com/abinit/abinit
#
#extra:
#    recipe-maintainers:
#        - gmatteo
