{% set name = "abiout" %}
#{% set version = "1.0.0" %}

package:
    name: {{ name }}
    #version: {{ version }}

build:
    number: 0
    skip: True  # [win]
    #rpaths:
    #  - lib/
    #  - lib64/

source:
    #git_tag: {{ version }}
    #git_url: https://github.com/abinit/abiout.git
    git_url: https://github.com/piti-diablotin/abiout.git

# sudo apt-get install g++ autotools-dev automake autoconf m4 libtool libncurses5-dev libjpeg8-dev libpng-dev libnetcdf-dev libcurl3-dev libfreetype6-dev libglfw3-dev libeigen3-dev fontconfig ttf-ubuntu-font-family libxml2-dev gnuplot-qt libyaml-cpp-dev libfftw3-dev libssh-dev cxxtest
requirements:
  host:
    - m4
    - autoconf
    - automake
    - libtool
    - cxxtest
    - {{ compiler('cxx') }}
    # 
    - curl
    - libssh2
    - libpng
    - libxml2
    - freetype
    - eigen
    - fftw
    - gnuplot
    - yaml-cpp
    - glfw
    - libnetcdf * nompi_*
    - hdf5 * nompi_*
    - spglib

  run:
    - curl
    - libssh2
    - libpng
    - libxml2
    - freetype
    - eigen
    - fftw
    - gnuplot
    - yaml-cpp
    - glfw
    - libnetcdf * nompi_*
    - hdf5 * nompi_*
    - spglib

test:
  commands:
    - test -x ${PREFIX}/bin/abiout

about:
    home: https://github.com/piti-diablotin/abiout
    license: GPL
    summary: "Agate is a tool engine to visualize and post-process data from ab-initio codes."
    description: |
        Agate is a tool engine to visualize and post-process data from ab-initio codes. 
        It is mainly designed to work with the Abinit DFT code. However, it can perfectly read 
        some VASP files and other commonly used format.
    doc_url: https://github.com/piti-diablotin/abiout
    dev_url: https://github.com/piti-diablotin/abiout

extra:
    recipe-maintainers:
        - gmatteo
