{% set name = "apscheduler" %}
{% set version = "2.1.0" %}
{% set md5 = "b837d23822fc46651862dd2186ec361a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: APScheduler-2.1.0.tar.gz
  url: https://pypi.python.org/packages/09/49/828c768c015ca3ca18b9a2e2029b6acc4c809e37c916659d3b54d69e67b1/APScheduler-2.1.0.tar.gz#md5=b837d23822fc46651862dd2186ec361a
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - apscheduler
    - apscheduler.jobstores
    - apscheduler.triggers
    - apscheduler.triggers.cron

about:
  home: http://pypi.python.org/pypi/APScheduler/
  license: MIT License
  summary: 'In-process task scheduler with Cron-like capabilities'
  license_family: MIT
