{% set version = "8.2.2" %}
{% set libxc_version = '2.2.2' %}
{% set mpi = 'mpich' %}

package:
    name: abinit
    version: {{ version }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    # See https://github.com/ContinuumIO/anaconda-issues/issues/739
    rpaths:
      - lib/
      - lib64/

source:
    fn: abinit-{{ version }}.tar.gz
    url: http://ftp.abinit.org/abinit-{{ version }}.tar.gz
    sha256: e43544a178d758b0deff3011c51ef7c957d7f2df2ce8543366d68016af9f3ea1

requirements:
  build:
    - gcc 
    - libgcc 
    - libgfortran
    - openblas
    - fftw
    - hdf5
    - netcdf4
    - netcdf-fortran
    - libxc {{ libxc_version }}
    - {{ mpi }}

  run:
    - libgcc 
    - libgfortran 
    - openblas
    - fftw
    - netcdf4
    - netcdf-fortran
    - libxc {{ libxc_version }}
    - {{ mpi }}

test:
  commands:
    - test -x ${PREFIX}/bin/abinit
    - test -x ${PREFIX}/bin/anaddb

about:
    home: http://www.abinit.org/
    license: GPL
    summary: "ABINIT is a quantum chemistry software based on the DFT (Density Functional Theory) method." 

    # The remaining entries in this section are optional, but recommended
    description: |
        ABINIT is a package whose main program allows one to find the total
        energy, charge density and electronic structure of systems made of 
        electrons and nuclei (molecules and periodic solids) within 
        Density Functional Theory (DFT), using pseudopotentials and a planewave
        or wavelet basis. ABINIT also includes options to optimize the geometry 
        according to the DFT forces and stresses, or to perform molecular dynamics 
        simulations using these forces, or to generate dynamical matrices,
        Born effective charges, and dielectric tensors, based on Density-Functional
        Perturbation Theory, and many more properties. Excited states can be computed 
        within the Many-Body Perturbation Theory (the GW approximation and the 
        Bethe-Salpeter equation), and Time-Dependent Density Functional Theory
        (for molecules). In addition to the main ABINIT code, different  utility programs are provided.
    doc_url: http://www.abinit.org/doc/helpfiles/for-v8.0/users/new_user_guide.html
    dev_url: https://github.com/abinit/abinit

extra:
    recipe-maintainers:
        - gmatteo
